---
title: "Machine Learning Repository"
author: C. Perez
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Repository Description

This repository houses an ongoing series of projects, exploring Machine Learning methods via small projects. There will typically be three files for each project; one will contain the code (**.R**), another will be markdown (**.Rmd**), and the last (**.pdf**) can be viewed directly in github. The (.pdf) file description includes the associated project description.
&nbsp;  


## Description of Files

#### kNN.r
A script file containing the code used in the ".rmd" file. 

#### kNN.rmd  
A markdown file with an output converted to ".pdf" for github viewer compatibility.  

#### kNN.pdf
Viewable output of kNN.rmd file. This projects applies kNN classification to speech recognition data and aims to identify the "best k" given the data present. Data used for this project can be found [here](https://archive.ics.uci.edu/ml/datasets/Speaker+Accent+Recognition).

#### naive_bayes.r
A naive bayes classification using text data: spam vs. no-spam prediction

#### decision_trees.r
A script file containing the code used in the ".rmd" file. 

#### decision_trees.rmd  
A markdown file with an output converted to ".pdf" for github viewer compatibility.  

#### decision_trees.pdf
Viewable output of decision_trees.rmd file. This projects applies 4 methods for decision tree classification to diabetes data and aims to improve each method given a business objective. Data used for this project can be found [here](https://archive.ics.uci.edu/ml/datasets/Early+stage+diabetes+risk+prediction+dataset).

#### README.rmd
This file creates a README.md file for the repository.

###### Note: data is not provided in the repository. Links are available in the README.


